#!/bin/bash

make

for i in 1 2 3 4 5 6 7 8 9 10
do

	./ORI_T01 < "$PWD/in/input$i.txt" > "$PWD/out/outTest$i.txt"
	
	if sdiff -s -Z <(cat -n "$PWD/out/outTest$i.txt") <(cat -n "$PWD/out/output$i.txt"); then
		printf "\nTeste $i - OK\n"
	else
		printf "\nTeste $i - NÃO PASSOU\n"
	fi


done
